print("Recipe Generator")
print()
randomFood = input("Name a food > ")
randomPlant = input("Name a type of plant > ")
cookingMethod = input("Name a method of cooking > ")
descriptiveWord = input("Name a word used to describe food > ")
DIYItem = input("Name a DIY item > ")
print()
print("Menu: ")
print(cookingMethod, randomFood, "with", descriptiveWord, randomPlant, "on a bed of", DIYItem)
