print("Getting to know you!")
print()
myName = input("What's your name?: ")
favouriteFood = input("What's your favourite food?: ")
favouriteMusic = input("What's your favourite music?: ")
home = input("Where do you live?: ")
print()
print("You are")
print(myName)
print("You're probably hungry for")
print(favouriteFood)
print("and you're definitely getting your groove on to")
print(favouriteMusic)
print("living in the amazing")
print(home)
